# Generated by Django 3.2.7 on 2021-10-25 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAdministrador',
            fields=[
                ('correo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('rut', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('estado_civil', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCliente',
            fields=[
                ('correo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('rut', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('estado_civil', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=10)),
                ('confirmar_contrasena', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEmpleado',
            fields=[
                ('correo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('rut', models.CharField(max_length=40)),
                ('fecha_nacimiento', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('estado_civil', models.CharField(max_length=10)),
                ('contrasena', models.CharField(max_length=10)),
                ('confirmar_contrasena', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroHora',
            fields=[
                ('idRegistro', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hora', models.CharField(max_length=10)),
                ('dia', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=10)),
                ('anno', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroProveedor',
            fields=[
                ('codigoProveedor', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('rut', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('giro', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroServicio',
            fields=[
                ('codigo_servicio', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=10)),
                ('precio', models.IntegerField()),
                ('observacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroHoraEmpleado',
            fields=[
                ('idRegistro', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hora', models.CharField(max_length=10)),
                ('dia', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=10)),
                ('anno', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registrocliente')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('idArticulo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('foto', models.TextField(max_length=290)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
